PassionProject/Models/BugCMSContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;


namespace PassionProject.Models
{
    public class BugCMSContext : DbContext
    {
        public BugCMSContext()
        {

        }

        public DbSet<BugReport> BugReports { get; set; }
        public DbSet<webproject> Webprojects { get; set; }
    }
}

PassionProject/Models/BugReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace PassionProject.Models
{
    public class BugReport
    {
        [Key]
        public int BugReportid { get; set; }

        public string Where { get; set; }

        public string What { get; set; }

        public string When { get; set; }

        public string Due { get; set; }

        public string status { get; set; }   
        
        //one webproject

        public virtual webproject webproject { get; set; }
    }
}

PassionProject/Models/webproject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace PassionProject.Models
{
    public class webproject
    {
        [Key]
        public int Webprojectid { get; set; }

        public string ProjectName { get; set; }

        public string ProjectLink { get; set; }

        public String AuthorName { get; set; }

        //one project to many bugs
        public virtual ICollection<BugReport> Bugs { get; set; }
    }
}

PassionProject/Controllers/BugReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using PassionProject.Models;

namespace PassionProject.Controllers
{
    public class BugReportController : Controller
    {
        private BugCMSContext Db = new BugCMSContext();
        // GET:create BugReport
        public ActionResult Create()
        {
            return View();
        }
        //Psot Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BugReportid,Where,What,When,Due,status")] BugReport bugrepo)
        {
            if (ModelState.IsValid)
            {
                Db.BugReports.Add(bugrepo);
                Db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(bugrepo);
        }

        public ActionResult List()
        {

            return View(Db.BugReports.ToList());
        }

        //get edit

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BugReport bugrepo = Db.BugReports.Find(id);
            if (bugrepo == null)
            {
                return HttpNotFound();
            }
            return View(bugrepo);
        }

        // POST: edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BugReportid,Where,What,When,Due,status")] BugReport bugrepo)
        {
            {
                if (ModelState.IsValid)
                {
                    Db.Entry(bugrepo).State = EntityState.Modified;
                    Db.SaveChanges();
                    return RedirectToAction("List");
                }
                return View(bugrepo);
            }
        }

        //Details get
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BugReport BugReport = Db.BugReports.Find(id);
            if (BugReport == null)
            {
                return HttpNotFound();
            }
            return View(BugReport);
        }


        //Delete get

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BugReport bugrepo = Db.BugReports.Find(id);
            if (bugrepo == null)
            {
                return HttpNotFound();
            }
            return View(bugrepo);
        }

        //Delete post

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BugReport bugrepo = Db.BugReports.Find(id);
            Db.BugReports.Remove(bugrepo);
            Db.SaveChanges();
            return RedirectToAction("List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

PassionProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PassionProject/Controllers/webprojectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using PassionProject.Models;

namespace PassionProject.Controllers
{
    public class webprojectController : Controller
    {
        private BugCMSContext Db = new BugCMSContext();
        // GET: webproject
        public ActionResult create()
        {
            return View();
        }

        //Psot Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Webprojectid,ProjectName,ProjectLink,AuthorName")] webproject webpro)
        {
            if (ModelState.IsValid)
            {
                Db.Webprojects.Add(webpro);
                Db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(webpro);
        }

        public ActionResult List()
        {

            return View(Db.Webprojects.ToList());
        }

        //get edit

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            webproject webrepo = Db.Webprojects.Find(id);
            if (webrepo == null)
            {
                return HttpNotFound();
            }
            return View(webrepo);
        }

        // POST: edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Webprojectid,ProjectName,ProjectLink,AuthorName")] webproject webpro)
        {
            {
                if (ModelState.IsValid)
                {
                    Db.Entry(webpro).State = EntityState.Modified;
                    Db.SaveChanges();
                    return RedirectToAction("List");
                }
                return View(webpro);
            }
        }


        //Details get
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            webproject webpro = Db.Webprojects.Find(id);
            if (webpro == null)
            {
                return HttpNotFound();
            }
            return View(webpro);
        }

        //Delete get

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            webproject webpro = Db.Webprojects.Find(id);
            if (webpro == null)
            {
                return HttpNotFound();
            }
            return View(webpro);
        }

        //Delete post

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            webproject webpro = Db.Webprojects.Find(id);
            Db.Webprojects.Remove(webpro);
            Db.SaveChanges();
            return RedirectToAction("List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

PassionProject/Views/BugReport/Create.cshtml
@model PassionProject.Models.BugReport

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BugReport</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Where, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Where, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Where, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.What, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.What, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.What, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.When, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.When, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.When, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Due, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Due, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Due, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/BugReport/Delete.cshtml
@model PassionProject.Models.BugReport

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BugReport</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Where)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Where)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.What)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.What)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.When)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.When)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Due)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Due)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

PassionProject/Views/BugReport/Details.cshtml
@model PassionProject.Models.BugReport

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BugReport</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Where)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Where)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.What)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.What)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.When)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.When)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Due)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Due)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BugReportid }) |
    @Html.ActionLink("Back to List", "List")
</p>

PassionProject/Views/BugReport/Edit.cshtml
@model PassionProject.Models.BugReport

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BugReport</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BugReportid)

        <div class="form-group">
            @Html.LabelFor(model => model.Where, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Where, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Where, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.What, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.What, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.What, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.When, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.When, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.When, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Due, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Due, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Due, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/BugReport/List.cshtml
@model IEnumerable<PassionProject.Models.BugReport>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Where)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.What)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.When)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Due)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Where)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.What)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.When)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Due)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BugReportid }) |
            @Html.ActionLink("Details", "Details", new { id=item.BugReportid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BugReportid })
        </td>
    </tr>
}

</table>

PassionProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PassionProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PassionProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PassionProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bug Tracker", "List", "BugReport", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bug Report", "List", "BugReport")</li>
                    <li>@Html.ActionLink("Project", "List", "webproject")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PassionProject/Views/webproject/Delete.cshtml
@model PassionProject.Models.webproject

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>webproject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

PassionProject/Views/webproject/Details.cshtml
@model PassionProject.Models.webproject

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>webproject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Webprojectid }) |
    @Html.ActionLink("Back to List", "List")
</p>

PassionProject/Views/webproject/Edit.cshtml
@model PassionProject.Models.webproject

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>webproject</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Webprojectid)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/webproject/List.cshtml
@model IEnumerable<PassionProject.Models.webproject>

@{
    ViewBag.Title = "Project List";
}

<h2>Project List</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectLink)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectLink)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Webprojectid }) |
            @Html.ActionLink("Details", "Details", new { id=item.Webprojectid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Webprojectid })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("[+]", "Create")
</p>

PassionProject/Views/webproject/create.cshtml
@model PassionProject.Models.webproject

@{
    ViewBag.Title = "create";
}

<h2>create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>webproject</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}